# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Build macOS

# file: .github/workflows/app-build-macos.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-05-24

on:
  workflow_call:
    inputs:
      environment:
        description: The environment name for the build jobs, or empty string for no environment.
        required: false
        type: string
        default: ''
      codesign-enabled:
        description: Whether to enable code signing and notarization steps.
        required: true
        type: boolean
      runs-on:
        description: The runner label to run this workflow on.
        required: true
        type: string
      DEVELOPER_DIR:
        description: The value of DEVELOPER_DIR environment variable.
        required: true
        type: string

    secrets:
      APP_STORE_CONNECT_ISSUER:
        required: false
      APP_STORE_CONNECT_KEY:
        required: false
      APP_STORE_CONNECT_KEY_ID:
        required: false
      MACOS_SIGNING_APPLICATION_IDENTITY:
        required: false
      MACOS_SIGNING_CERT_PASSWORD:
        required: false
      MACOS_SIGNING_CERT:
        required: false

permissions: {}

jobs:
  build-macos-universal:
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs-on}}
    timeout-minutes: 180

    permissions:
      contents: read

    env:
      DEVELOPER_DIR: '${{ inputs.DEVELOPER_DIR }}'

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies via Homebrew
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          brew install xcodegen

      - name: Set up macOS Signing Certificates
        if: inputs.codesign-enabled
        id: codesign
        uses: ./.github/actions/setup-macos-codesigning
        with:
          MACOS_SIGNING_APPLICATION_IDENTITY: ${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}
          MACOS_SIGNING_CERT: ${{ secrets.MACOS_SIGNING_CERT }}
          MACOS_SIGNING_CERT_PASSWORD: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}

      - name: Generate project
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          xcodegen generate

      - name: Build apps
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CODESIGN_TEAM: ${{ steps.codesign.outputs.CODESIGN_TEAM }}
          MACOS_SIGNING_APPLICATION_IDENTITY: ${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}
        run: |
          for target in LiveStreamerAppletYT; do
            XCODEBUILD_ARCHIVE_ARGS=(
              -project LiveStreamerApplet.xcodeproj
              -scheme "$target"
              -configuration Release
              -archivePath "build/$target.xcarchive"
              DEVELOPMENT_TEAM="$CODESIGN_TEAM"
              CODE_SIGN_IDENTITY="$MACOS_SIGNING_APPLICATION_IDENTITY" \
              CODE_SIGN_STYLE=Manual
            )
            xcodebuild archive "${XCODEBUILD_ARCHIVE_ARGS[@]}"
          done

      - name: Upload apps
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: live-streamer-applet-apps-${{ github.run_id }}
          path: |
            build/*.xcarchive/Products/Applications/*.app
          if-no-files-found: warn
          retention-days: 7

