# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: App CI

# file: .github/workflows/app.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-05-24

on:
  pull_request:
    branches: [main]
  merge_group:
  push:
    branches: [main]
    tags: ["*"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos:
    permissions:
      contents: read
    uses: ./.github/workflows/app-build-macos.yml
    with:
      environment: ${{ github.event_name == 'push' && 'production-macos' || '' }}
      codesign-enabled: ${{ github.event_name == 'push' }}
      runs-on: macos-26
      DEVELOPER_DIR: /Applications/Xcode_26.5.0.app
    secrets: inherit

  accept-apps:
    name: Accept Apps CI
    needs: [build-macos]
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - run: echo OK
